name: Credo Linting

on: pull_request

jobs:
  compilation:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        elixir: [1.15]
        otp: [26]
    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-elixir@v1
        with:
          elixir-version: ${{ matrix.elixir }}
          otp-version: ${{ matrix.otp }}
      - uses: actions/cache@v1
        id: mix-cache-lint
        with:
          path: deps
          key: ${{ runner.os }}-${{ matrix.otp}}-%{{ matrix.elixir }}-mix-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
      - name: Install Mix depencies
        if: steps.mix-cache-lint.outputs.cache-hit != 'true'
        run: mix deps.get
      - name: ====> Compilation
        run: mix credo --strict
